In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [3]:
digits = load_digits()

In [4]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

## Using train_test_split

In [5]:
from sklearn.model_selection import train_test_split

in this way, each time I run it, the accuracy will be different.

In [6]:
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

**Logistic Regression**

In [7]:
lr = LogisticRegression(solver='liblinear', multi_class='auto')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9425925925925925

**SVM**

In [8]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.6129629629629629

**Random Forest**

In [9]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9574074074074074

## Using k_fold

In [10]:
from sklearn.model_selection import KFold

how it works...

In [11]:
# define the number of splits you want
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


the kfold will split you dataset in n_splits, using the first part to test and the rest to train; the middle part to test and the rest to train; and so on...


**K FOLD**

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
k_fold = KFold(n_splits=3, shuffle=True, random_state=0)

**Logistic Regression**

In [15]:
clf = LogisticRegression(solver='liblinear', multi_class='auto')

scoring = 'accuracy'
score = cross_val_score(clf, digits.data, digits.target, cv=k_fold, n_jobs=1, scoring=scoring)

print(score)
print(round(np.mean(score)*100,2))

[0.95158598 0.95826377 0.95993322]
95.66


**SVM**

In [16]:
clf = SVC(gamma='scale')

scoring = 'accuracy'
score = cross_val_score(clf, digits.data, digits.target, cv=k_fold, n_jobs=1, scoring=scoring)

print(score)
print(round(np.mean(score)*100,2))

[0.98831386 0.98831386 0.98831386]
98.83


**Random Forest**

In [17]:
clf = RandomForestClassifier(n_estimators=13)

scoring = 'accuracy'
score = cross_val_score(clf, digits.data, digits.target, cv=k_fold, n_jobs=1, scoring=scoring)

print(score)
print(round(np.mean(score)*100,2))

[0.93656093 0.94657763 0.94991653]
94.44
